version: "3.9"

services:
  server:
    container_name: code-sync-server
    build:
      context: ./server
      dockerfile: Dockerfile
      # target removed – uses final production image
    ports:
      - "3000:3000"
    networks:
      - Code-Sync
    restart: always
    command: npm run start

  client:
    container_name: code-sync-client
    build:
      context: ./client
      dockerfile: Dockerfile
      # target removed – uses final production image
    ports:
      - "5173:5173"
    networks:
      - Code-Sync
    depends_on:
      - server
    restart: always
    command: serve -s dist -l 5173  # adjust if using a different static server

networks:
  Code-Sync:
    driver: bridge
