name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "Deploying Code Sync..."

            # Pull latest Docker images
            docker pull nitheesh2005/code-sync-server:latest
            docker pull nitheesh2005/code-sync-client:latest

            # Stop and remove old containers
            docker stop code-sync-server || true
            docker rm code-sync-server || true
            docker stop code-sync-client || true
            docker rm code-sync-client || true

            # Start new containers
            docker run -d --name code-sync-server -p 3000:3000 nitheesh2005/code-sync-server:latest
            docker run -d --name code-sync-client -p 5173:5173 nitheesh2005/code-sync-client:latest
